set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12)
set(0,...
    'defaultAxesTickLabelInterpreter','latex',...
    'defaultLegendInterpreter','latex',...
    'defaultTextInterpreter','latex',...
    'defaultAxesFontName','CMU Serif',...
    'defaultLegendFontName','CMU Serif',...
    'defaultTextFontName','CMU Serif')
clear, close all, clc, rng(0);